### ISSUE TITLE
Liveskalierung der Planeten

### ISSUE THREAD

**Issue by maiktheknife** [BenjaminReenK/ComputerGrafik#10]
Herr Isreal hat sich heute in der Übung die Möglichkeit gewünscht die Planeten+Sonne, eh aktuelle nicht komplett maßstandsgerecht, über z.B. Tastenkürzel während der Animation skalieren zu können. 
Sodass sie dann quasi aneinander stoßen.

**Comment by BenjaminReenK** [comment]
done in Commit #15
